# Generated by Django 5.1.1 on 2024-09-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='hash_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
